import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import test from 'node:test'

const root = process.cwd()
const readProjectFile = (...parts) => readFileSync(join(root, ...parts), 'utf8')

test('daily Metrics visit tracking is server-side and excludes the admin', () => {
  const route = readProjectFile('app', 'api', 'analytics', 'visit', 'route.ts')
  const locationSheetRoute = readProjectFile('app', 'api', 'analytics', 'location-sheet', 'route.ts')
  const analyticsProvider = readProjectFile('components', 'AnalyticsProvider.tsx')
  const homeClient = readProjectFile('components', 'HomeClient.tsx')

  assert.match(route, /auth\.getUser\(\)/)
  assert.match(route, /createAdminSupabase/)
  assert.match(route, /5a018580-6558-44fc-a621-1fa2506e9d5e/)
  assert.match(route, /user_visit_events/)
  assert.match(route, /path\.slice\(0, 200\)/)
  assert.match(route, /status: 401/)
  assert.match(route, /status: 503/)
  assert.match(route, /status: 500/)
  assert.match(locationSheetRoute, /location_sheet_view_events/)
  assert.match(locationSheetRoute, /from_location/)
  assert.match(analyticsProvider, /fetch\('\/api\/analytics\/visit'/)
  assert.match(analyticsProvider, /supabase\.auth\.getSession\(\)/)
  assert.match(analyticsProvider, /VISIT_RETRY_DELAYS_MS/)
  assert.match(analyticsProvider, /page_path: pathname/)
  assert.match(homeClient, /fetch\('\/api\/analytics\/location-sheet'/)
})

test('daily Metrics migration schedules the KST Discord delivery and applies all exclusions', () => {
  const migration = readProjectFile('supabase', 'migrations', '20260807022519_daily_metrics_discord_alert.sql')
  const refinementMigration = readProjectFile('supabase', 'migrations', '20260807040353_refine_active_room_metric.sql')
  const visitorMigration = readProjectFile('supabase', 'migrations', '20260807153527_use_page_visits_for_daily_visitors.sql')
  const metricsMigrations = `${migration}\n${refinementMigration}\n${visitorMigration}`

  assert.match(metricsMigrations, /create extension if not exists pg_cron/)
  assert.match(metricsMigrations, /gatita-daily-metrics-discord/)
  assert.match(metricsMigrations, /'3 15 \* \* \*'/)
  assert.match(metricsMigrations, /1511605519322972320/)
  assert.match(metricsMigrations, /discord_bot_token/)
  assert.match(metricsMigrations, /5a018580-6558-44fc-a621-1fa2506e9d5e/)
  assert.match(metricsMigrations, /user_visit_events/)
  assert.match(metricsMigrations, /room_participant_events/)
  assert.match(metricsMigrations, /location_sheet_view_events/)
  assert.match(metricsMigrations, /pwa_installed_at/)
  assert.match(metricsMigrations, /금일 방문 유저/)
  assert.match(metricsMigrations, /금일 활성 방/)
  assert.match(metricsMigrations, /금일 합승/)
  assert.match(metricsMigrations, /최근 방문 %s/)
  assert.match(metricsMigrations, /timestamp '2026-06-15 00:00:00'/)
  assert.match(metricsMigrations, /v_top_window_start/)
  assert.match(metricsMigrations, /from public\.room_participant_events e/)
  assert.match(metricsMigrations, /e\.event_type = 'joined'/)
  assert.match(metricsMigrations, /into v_mau[\s\S]*from public\.location_sheet_view_events e/)
  assert.match(refinementMigration, /into v_today_active_rooms[\s\S]*?from public\.messages msg[\s\S]*?private\.room_had_two_participants\(m\.id, v_day_end\)/)
  assert.match(refinementMigration, /into v_previous_active_rooms[\s\S]*?from public\.messages msg[\s\S]*?private\.room_had_two_participants\(m\.id, v_previous_day_end\)/)
  assert.doesNotMatch(refinementMigration, /into v_today_active_rooms[\s\S]*?location_sheet_view_events/)
  assert.match(visitorMigration, /into v_today_visitors[\s\S]*?from public\.user_visit_events e[\s\S]*?e\.visited_at >= v_day_start/)
  assert.match(visitorMigration, /into v_previous_visitors[\s\S]*?from public\.user_visit_events e[\s\S]*?e\.visited_at >= v_previous_day_start/)
  const visitorQueries = visitorMigration.slice(
    visitorMigration.indexOf('into v_today_visitors'),
    visitorMigration.indexOf('into v_mau')
  )
  assert.doesNotMatch(visitorQueries, /from public\.room_participant_events e/)
  assert.match(metricsMigrations, /order by visit_count desc, last_visit_at desc, e\.user_id/)
  assert.match(metricsMigrations, /order by c\.visit_count desc, c\.last_visit_at desc, c\.user_id/)
  assert.doesNotMatch(metricsMigrations, /전일 TOP3 누적 방문 합계 대비/)
  assert.match(metricsMigrations, /else '\+0'/)
  assert.match(metricsMigrations, /'\+0\.0%p'/)
  assert.match(metricsMigrations, /'embeds', jsonb_build_array/)
  assert.match(metricsMigrations, /'fields', v_fields/)
  assert.match(metricsMigrations, /'inline', true/)
  assert.match(metricsMigrations, /'name', '👥 유저 수'/)
  assert.match(metricsMigrations, /\*\*%s명\*\*/)
  assert.doesNotMatch(metricsMigrations, /전일 대비 \*\*%s/)
  assert.match(metricsMigrations, /'%s\. %s · %s회 \(최근 방문 %s\)'/)
  assert.doesNotMatch(metricsMigrations, /'%s\. \*\*%s\*\* · \*\*%s회\*\* \(최근 방문 %s\)'/)
})
