import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import test from 'node:test'
import assert from 'node:assert/strict'

const root = process.cwd()
const readProjectFile = (...parts) => readFileSync(join(root, ...parts), 'utf8')

test('profile onboarding stores phone without SMS MFA and derives department from Google profile', () => {
  const signup = readProjectFile('components', 'auth', 'SignupForm.tsx')
  const auth = readProjectFile('lib', 'auth.ts')
  const completeRoute = readProjectFile('app', 'api', 'profile', 'complete', 'route.ts')
  const meRoute = readProjectFile('app', 'api', 'profile', 'me', 'route.ts')
  const schema = readProjectFile('supabase_schema.sql')
  const types = readProjectFile('lib', 'supabase.ts')

  assert.doesNotMatch(signup, /auth\.mfa/, 'signup should not use Supabase SMS MFA')
  assert.doesNotMatch(signup, /인증번호/, 'signup should not render SMS code UI')
  assert.doesNotMatch(signup, /id:\s*['"]department['"]/, 'department should not be a manual onboarding step')
  assert.match(auth, /extractGachonProfileFromMetadata/, 'auth helpers should parse Google profile metadata')
  assert.match(signup, /extractGachonProfileFromMetadata/, 'signup should use parsed Google profile metadata')
  assert.match(signup, /\/api\/profile\/complete/, 'signup should complete private profile through a server route')
  assert.match(completeRoute, /\.upsert\(/, 'profile completion should be idempotent for duplicate submits')
  assert.doesNotMatch(completeRoute, /\.delete\(\)\.eq\('id', authUser\.id\)/, 'duplicate profile completion must not delete a successfully created public user')
  assert.match(meRoute, /!publicProfile \|\| !privateProfile \|\| !privateProfile\.onboarded_at/, 'profile completion should be gated on onboarded_at')
  assert.match(signup, /bank_name/, 'signup should collect bank name')
  assert.match(signup, /account_number/, 'signup should collect account number')
  assert.match(signup, /account_holder/, 'signup should collect account holder')
  assert.match(signup, /placeholder:\s*'가천존예여신'/, 'nickname placeholder should use the requested sample nickname')

  assert.match(schema, /create table public\.user_private_profiles/i, 'schema should split private identity fields out of users')
  assert.doesNotMatch(schema, /create table public\.user_payout_accounts/i, 'payout account table should be merged into private profiles')
  assert.match(schema, /onboarded_at/i, 'private profiles should track onboarding completion')
  assert.match(schema, /bank_name/i, 'private profiles should hold merged payout bank fields')
  assert.match(schema, /grant select \(id, nickname, nickname_updated_at, department, avatar_url, created_at, updated_at\)\s+on table public\.users to authenticated/i, 'public users table should expose only public profile columns')
  assert.match(schema, /Users can read own private profile/i, 'schema should allow users to read only their own private profile')
  assert.doesNotMatch(schema, /Room participants can read creator payout accounts/i, 'room participants must not read payout accounts directly through RLS')
  assert.match(types, /export type PayoutAccount/, 'Supabase types should expose payout accounts')
})

test('settings lets users edit payout account while keeping phone immutable', () => {
  const settings = readProjectFile('app', 'settings', 'page.tsx')
  const signup = readProjectFile('components', 'auth', 'SignupForm.tsx')
  const bankFields = readProjectFile('components', 'BankAccountFields.tsx')
  const banks = readProjectFile('lib', 'banks.ts')

  assert.match(settings, /\/api\/profile\/payout/, 'settings should update payout via the server route')
  assert.match(settings, /BankSelectField/, 'settings should render bank dropdown')
  assert.match(settings, /AccountNumberSegmentField/, 'settings should render segmented account number boxes')
  assert.match(signup, /BankSelectField/, 'signup should use the shared bank selector')
  assert.match(signup, /AccountNumberSegmentField/, 'signup should use segmented account number boxes')
  assert.match(signup, /정산 계좌를 등록해주세요/, 'payout section should explain the payout context')
  assert.match(signup, /presentation="sheet"/, 'signup should use the mobile bottom-sheet bank picker')
  assert.match(signup, /showErrorMessage=\{false\}/, 'signup should keep bank picker errors in the section field chrome')
  assert.match(signup, /방을 개설하면 같은 방 참여자에게 공개될 수 있습니다/, 'bank field should disclose payout visibility')
  assert.match(signup, /정산 계좌는 방을 개설한 경우 같은 방 참여자에게만 표시됩니다/, 'review should summarize payout visibility before submit')
  assert.doesNotMatch(signup, /방장이 되면 같은 방 참여자에게 공개됩니다/, 'signup should not use the older payout exposure copy')
  assert.doesNotMatch(signup, /방장으로 참여하면 계좌번호가 같은 방 멤버에게 노출될 수 있습니다\./, 'account number step should not duplicate the exposure warning below the field')
  assert.match(bankFields, /BANK_OPTIONS/, 'bank fields should be driven by shared bank metadata')
  assert.match(bankFields, /logoSrc/, 'bank dropdown should render real bank logo images when available')
  assert.match(bankFields, /직접 입력/, 'bank dropdown should allow manual bank name entry')
  assert.match(bankFields, /onCustomBankChange/, 'manual bank entry should feed the same bank name value')
  assert.doesNotMatch(bankFields, /형식:/, 'account number helper text should not show format copy under the inputs')
  assert.doesNotMatch(bankFields, /absolute left-0 right-0 top-full/, 'bank dropdown should stay in document flow so mobile pages can scroll around it')
  assert.match(bankFields, /data-bank-dropdown-list/, 'bank dropdown list should be explicitly identifiable for scroll-safe styling')
  assert.match(bankFields, /data-bank-dropdown-list[^>]*max-h-64[^>]*overflow-y-auto/, 'bank dropdown should expose only a short scrollable list on mobile')
  assert.match(bankFields, /data-bank-sheet-list/, 'mobile bank sheet should expose its own scrollable list')
  assert.match(bankFields, /aria-labelledby="bank-picker-title"/, 'mobile bank sheet should be announced as a dialog')
  assert.match(bankFields, /aria-label=\{`계좌번호 \$\{index \+ 1\}번째 입력칸`\}[\s\S]*text-base/, 'account number boxes should avoid iOS Safari focus zoom')
  assert.match(bankFields, /placeholder=\{'0'\.repeat\(length\)\}/, 'account segment placeholders should match each selected bank segment length')
  assert.match(banks, /name:\s*'카카오뱅크'[\s\S]*segments:\s*\[4,\s*2,\s*7\]/, 'KakaoBank should use XXXX-XX-XXXXXXX')
  assert.match(banks, /logoSrc:\s*['"]\/bank-logos\/kakaobank\.svg['"]/, 'KakaoBank should use a reliable local brand icon')
  assert.match(settings, /account_holder/, 'settings should render account holder input')
  assert.match(settings, /className="input-field settings-input"/, 'settings account inputs should use the shared input styling')
  assert.match(settings, /\{\s*label:\s*'전화번호',\s*value:\s*user\.phone\s*\}/, 'phone number should remain immutable as a read-only settings row')
  assert.doesNotMatch(settings, /type="tel"[\s\S]*onChange/, 'settings should not expose an editable phone input')
})

test('profile onboarding uses section-based mobile form and keeps account number segmentation stable', () => {
  const signup = readProjectFile('components', 'auth', 'SignupForm.tsx')
  const settings = readProjectFile('app', 'settings', 'page.tsx')
  const bankFields = readProjectFile('components', 'BankAccountFields.tsx')
  const banks = readProjectFile('lib', 'banks.ts')

  assert.match(signup, /hasCheckedSessionRef/, 'signup session bootstrap should run only once so parent rerenders do not reset onboarding progress')
  assert.doesNotMatch(signup, /\[onSuccess,\s*supabase\]/, 'signup session bootstrap must not rerun whenever parent callbacks are recreated')
  assert.match(signup, /SIGNUP_SECTIONS/, 'signup should use section-based onboarding instead of a stacked question transcript')
  assert.match(signup, /type SignupSectionId = 'basic' \| 'payout' \| 'review'/, 'signup should use a three-step profile setup flow')
  assert.match(signup, /shortTitle:\s*'기본 정보'/, 'signup should keep a basic information section')
  assert.match(signup, /학교 계정 정보를 불러왔어요\. 전화번호는 가입 후 변경할 수 없어요\./, 'basic section should use friendlier fixed-name copy')
  assert.doesNotMatch(signup, /이름은 학교 계정 기준으로 고정되고, 전화번호는 가입 후 변경할 수 없습니다\./, 'basic section should not use stiff fixed-name copy')
  assert.match(signup, /fields:\s*\['phone', 'nickname'\]/, 'basic section should collect phone and nickname together')
  assert.match(signup, /ReadOnlyProfileRow/, 'signup should show the Google name as read-only profile context')
  assert.doesNotMatch(signup, /fields:\s*\['name', 'phone'\]/, 'basic section should not render name as an editable field')
  assert.doesNotMatch(signup, /id:\s*'profile'/, 'nickname should not live in a separate profile step')
  assert.doesNotMatch(signup, /autoComplete=\{fieldId === 'name' \? 'name' : 'off'\}/, 'signup should not expose an editable name input')
  assert.doesNotMatch(signup, /name:\s*formData\.name\.trim\(\)/, 'submit should not assume the read-only Google name is already hydrated')
  assert.match(signup, /const signupGoogleProfile = extractGachonProfileFromMetadata\(sessionData\.session\.user\.user_metadata\)/, 'submit should fall back to Google profile metadata for read-only name')
  assert.match(signup, /const resolvedName = \(formData\.name \|\| signupGoogleProfile\.name\)\.trim\(\)/, 'submit should resolve a non-editable name before sending the payload')
  assert.match(signup, /shortTitle:\s*'정산 계좌'/, 'signup should group bank fields into one payout section')
  assert.match(signup, /shortTitle:\s*'마지막 확인'/, 'signup should include a final review section')
  assert.match(signup, /isLastStep \? \(\s*'가입 완료'/, 'final CTA should stay concise because consent is handled by the checkboxes')
  assert.doesNotMatch(signup, /동의하고 가입 완료/, 'final CTA should not repeat consent copy')
  assert.doesNotMatch(signup, /SIGNUP_STEPS\.slice\(0, currentStep \+ 1\)/, 'signup should not stack all previous questions above the active input')
  assert.match(signup, /formatPhoneNumber/, 'signup should normalize one phone input into 010-0000-0000 format')
  assert.match(signup, /autoComplete="tel"/, 'phone input should cooperate with iOS contact autofill')
  assert.match(signup, /inputMode="numeric"/, 'phone input should keep the numeric keyboard')
  assert.match(signup, /--signup-viewport-height/, 'profile setup should track the visual viewport for iOS keyboard scrolling')
  assert.match(signup, /window\.visualViewport\?\.height \?\? window\.innerHeight/, 'profile setup should resize around the iOS visual viewport')
  assert.match(signup, /style=\{\{ height: 'var\(--signup-viewport-height, 100dvh\)' \}\}/, 'profile setup should use a bounded scroll container instead of a static screen height')
  assert.match(signup, /overflow-y-auto/, 'profile setup content should be scrollable while the keyboard is open')
  assert.match(signup, /<footer className="shrink-0 border-t border-gray-100 bg-white\/95/, 'profile setup should keep the primary CTA in a keyboard-aware sticky footer')
  assert.match(signup, /onFocusCapture=\{focusCurrentSection\}/, 'profile setup should keep focused inputs visible above the keyboard')
  assert.match(signup, /SIGNUP_SECTIONS\.slice\(0, currentStep\)/, 'completed sections should be summarized compactly above the active section')
  assert.match(bankFields, /inputRefs\.current = inputRefs\.current\.slice\(0, segments\.length\)/, 'account segment refs should be trimmed when bank format changes')
  assert.match(bankFields, /const pastedSegments = splitAccountNumberForBank\(bankName, digits\)/, 'pasted account numbers should be repartitioned by selected bank')
  assert.match(bankFields, /handleSegmentKeyDown/, 'account segment inputs should handle backward focus without crashing')
  assert.match(banks, /formatAccountNumberForBank/, 'bank helpers should format stored account numbers for display')
  assert.match(settings, /\.\.\.\(field === 'bank_name' \? \{ account_number: '' \} : \{\}\)/, 'changing bank should clear a stale account number format')
})

test('profile onboarding requires a separate no paid private-car transport compliance check', () => {
  const signup = readProjectFile('components', 'auth', 'SignupForm.tsx')

  assert.match(signup, /hasAcceptedUsageRules/, 'signup should track service-use compliance separately from legal/privacy consent')
  assert.match(signup, /usageRules/, 'signup should validate the service-use compliance checkbox as its own review error')
  assert.match(signup, /&lt;같이타&gt;를 자가용 차량으로 돈을 받고 동승자를 태워주는 데 사용하지 않겠습니다\./, 'compliance copy should clearly prohibit paid private-car rides')
  assert.match(signup, /className="line-clamp-2/, 'compliance copy should be visually capped at two lines')
  assert.doesNotMatch(signup, /렌터카/, 'compliance copy should remove the older rental-car wording')
  assert.doesNotMatch(signup, /수고비/, 'compliance copy should remove the older compensation wording')
  assert.doesNotMatch(signup, /택시 동승 및 실제 공동 이용 비용 정산 조율/, 'compliance copy should remove the extra explanatory sentence')
  assert.match(signup, /개인정보처리방침[\s\S]*에 동의합니다\.[\s\S]*&lt;같이타&gt;를 자가용 차량으로 돈을 받고/, 'service-use compliance should render below the legal/privacy consent checkbox')
  assert.match(signup, /hasAcceptedRequiredTerms && hasAcceptedUsageRules/, 'the final CTA should require both legal/privacy consent and service-use compliance')
})
